# Generated by Django 6.0.5 on 2026-06-14 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportexportjob',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='error_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to='reports/exports/'),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='generation_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='report_version',
            field=models.CharField(default='day25-v1', max_length=16),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='requested_timezone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportexportjob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reportexportjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], default='ready', max_length=12),
        ),
        migrations.AddIndex(
            model_name='reportexportjob',
            index=models.Index(fields=['user', 'generation_fingerprint'], name='analytics_r_user_id_6ea5ff_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportjob',
            index=models.Index(fields=['status', 'expires_at'], name='analytics_r_status_0d4ffd_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportexportjob',
            constraint=models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='report_export_progress_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='reportexportjob',
            constraint=models.UniqueConstraint(condition=models.Q(('generation_fingerprint', ''), _negated=True), fields=('user', 'generation_fingerprint'), name='unique_report_export_fingerprint_per_user'),
        ),
    ]
