# Generated by Django 6.0.5 on 2026-06-04 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=64)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('content_snippet', models.TextField(blank=True)),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
                ('tab_switch_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='tracking_br_session_69cca1_idx'), models.Index(fields=['session_id', 'event_type'], name='tracking_br_session_f51875_idx'), models.Index(fields=['domain'], name='tracking_br_domain_6e05db_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField()),
                ('batch_size', models.PositiveIntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['processed', 'received_at'], name='tracking_ev_process_22fa04_idx'), models.Index(fields=['session_id', 'received_at'], name='tracking_ev_session_c9a90d_idx')],
            },
        ),
    ]
