# Generated by Django 6.0.5 on 2026-06-05 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField()),
                ('warning_level', models.PositiveSmallIntegerField()),
                ('warning_type', models.CharField(choices=[('normal_blacklist', 'Normal Blacklist'), ('deep_work_ai', 'Deep Work AI'), ('idle', 'Idle'), ('tab_switch', 'Tab Switch'), ('manual', 'Manual')], max_length=32)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('message', models.TextField(blank=True)),
                ('was_acknowledged', models.BooleanField(default=False)),
                ('triggered_auto_pause', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('browser_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='tracking.browserevent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='tracking_wa_session_d936a0_idx'), models.Index(fields=['warning_level'], name='tracking_wa_warning_8c3a0c_idx'), models.Index(fields=['warning_type'], name='tracking_wa_warning_09ba06_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('warning_level__in', [1, 2, 3])), name='warning_event_level_between_1_and_3')],
            },
        ),
    ]
