# Generated by Django 6.0.5 on 2026-06-09 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_warningevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='warningevent',
            name='auto_pause_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warningevent',
            name='decision_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warningevent',
            name='decision_state',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='warningevent',
            name='reason_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='WarningCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField()),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('mode', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('warning_1_sent', 'Warning 1 Sent'), ('warning_2_sent', 'Warning 2 Sent'), ('warning_3_sent', 'Warning 3 Sent'), ('resolved', 'Resolved'), ('completed', 'Completed'), ('auto_pause_required', 'Auto Pause Required'), ('cancelled', 'Cancelled')], max_length=32)),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('decision_state', models.CharField(blank=True, max_length=32)),
                ('decision_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('auto_pause_required', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('NONE', 'None'), ('AUTO_PAUSE', 'Auto Pause')], default='NONE', max_length=32)),
                ('next_warning_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warning_cycles', to='tracking.browserevent')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='warningevent',
            name='warning_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='tracking.warningcycle'),
        ),
        migrations.AddIndex(
            model_name='warningevent',
            index=models.Index(fields=['warning_cycle', 'warning_level'], name='tracking_wa_warning_31bbbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='warningevent',
            constraint=models.UniqueConstraint(condition=models.Q(('warning_cycle__isnull', False)), fields=('warning_cycle', 'warning_level'), name='unique_warning_level_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='warningcycle',
            index=models.Index(fields=['session_id', 'status'], name='tracking_wa_session_3bc19a_idx'),
        ),
        migrations.AddIndex(
            model_name='warningcycle',
            index=models.Index(fields=['session_id', 'started_at'], name='tracking_wa_session_1207bd_idx'),
        ),
        migrations.AddIndex(
            model_name='warningcycle',
            index=models.Index(fields=['idempotency_key'], name='tracking_wa_idempot_f1cb29_idx'),
        ),
        migrations.AddConstraint(
            model_name='warningcycle',
            constraint=models.CheckConstraint(condition=models.Q(('current_level__in', [1, 2, 3])), name='warning_cycle_level_between_1_and_3'),
        ),
        migrations.AddConstraint(
            model_name='warningcycle',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['warning_1_sent', 'warning_2_sent', 'warning_3_sent', 'auto_pause_required'])), fields=('session_id',), name='one_active_warning_cycle_per_session'),
        ),
    ]
