# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_warningevent_auto_pause_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warningcycle",
            name="decision_source",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="warningevent",
            name="decision_source",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
