# Generated by Django 6.0.5 on 2026-06-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_warning_decision_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='browserevent',
            name='client_event_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='browserevent',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='browserevent',
            index=models.Index(fields=['session_id', 'occurred_at'], name='tracking_br_session_8f1e01_idx'),
        ),
        migrations.AddIndex(
            model_name='browserevent',
            index=models.Index(fields=['session_id', 'client_event_id'], name='tracking_br_session_d12a4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='browserevent',
            constraint=models.UniqueConstraint(condition=models.Q(('client_event_id__isnull', False)), fields=('session_id', 'client_event_id'), name='unique_browser_event_client_id_per_session'),
        ),
    ]
