# Generated by Django 6.0.5 on 2026-06-04 13:53

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('extension_version', models.CharField(max_length=64)),
                ('browser', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['user_id', 'last_seen'], name='extension_e_user_id_23ae4a_idx'), models.Index(fields=['is_active', 'last_seen'], name='extension_e_is_acti_f5ebdd_idx')],
            },
        ),
    ]
