# Generated by Django 6.0.5 on 2026-06-08 15:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extension', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=253)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium')], default='medium', max_length=12)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'domain'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_default', True), ('user__isnull', True)), models.Q(('is_default', False), ('user__isnull', False)), _connector='OR'), name='blacklist_owner_matches_type'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('domain',), name='unique_default_blacklist_domain'), models.UniqueConstraint(condition=models.Q(('is_default', False)), fields=('user', 'domain'), name='unique_custom_blacklist_domain_per_user')],
            },
        ),
    ]
