# Generated by Django 6.0.5 on 2026-07-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('session_reminder', 'Session reminder'), ('weekly_summary', 'Weekly summary'), ('deep_work_suggestion', 'Deep work suggestion'), ('document_ai_completed', 'Document AI completed'), ('test', 'Test')], max_length=32),
        ),
    ]
