# Generated by Django 6.0.5 on 2026-06-13 13:14

from django.db import migrations, models


def normalize_legacy_music_track(apps, schema_editor):
    UserPreference = apps.get_model("users", "UserPreference")
    UserPreference.objects.filter(music_track="white-noise").update(
        music_track="white_noise",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_week4_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='custom_playlist_provider',
            field=models.CharField(choices=[('none', 'None'), ('spotify', 'Spotify'), ('youtube_music', 'YouTube Music'), ('direct_audio', 'Direct Audio'), ('external', 'External')], default='none', max_length=24),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='music_autoplay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='use_custom_playlist',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(normalize_legacy_music_track, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userpreference',
            name='custom_playlist_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='music_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='music_track',
            field=models.CharField(choices=[('none', 'None'), ('lofi', 'Lo-fi'), ('rain', 'Rain'), ('forest', 'Forest'), ('cafe', 'Cafe'), ('white_noise', 'White Noise')], default='none', max_length=24),
        ),
    ]
