# Generated by Django 6.0.5 on 2026-06-14 02:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userpreference_custom_playlist_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDataExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('export_format', models.CharField(choices=[('zip', 'ZIP')], default='zip', max_length=8)),
                ('file', models.FileField(blank=True, max_length=255, upload_to='account-exports/')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('export_version', models.CharField(default='day26-v1', max_length=16)),
                ('generation_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'requested_at'], name='users_accou_user_id_d64d22_idx'), models.Index(fields=['user', 'generation_fingerprint'], name='users_accou_user_id_c1af15_idx'), models.Index(fields=['status', 'expires_at'], name='users_accou_status_88f066_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 100)), name='account_export_progress_between_0_100'), models.UniqueConstraint(condition=models.Q(('generation_fingerprint', ''), _negated=True), fields=('user', 'generation_fingerprint'), name='unique_account_export_fingerprint_per_user')],
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_identifier_snapshot', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('confirmed', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('deletion_version', models.CharField(default='day26-v1', max_length=16)),
                ('audit_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_deletion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='users_accou_user_id_1028bb_idx'), models.Index(fields=['status', 'scheduled_for'], name='users_accou_status_ade205_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'processing'])), fields=('user',), name='unique_active_account_deletion_job_per_user')],
            },
        ),
    ]
