# Generated by Django 6.0.5 on 2026-06-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_accountdataexportjob_accountdeletionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdeletionjob',
            name='status_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountdeletionjob',
            name='status_token_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='accountdeletionjob',
            index=models.Index(fields=['status_token_expires_at'], name='users_accou_status__505987_idx'),
        ),
    ]
