# Generated by Django 6.0.6 on 2026-06-05 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('focus_sessions', '0002_seed_goal_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_score', models.PositiveSmallIntegerField()),
                ('focus_state', models.CharField(choices=[('deep-focus', 'Deep Focus'), ('focused', 'Focused'), ('average', 'Average'), ('distracted', 'Distracted'), ('highly-distracted', 'Highly Distracted')], max_length=32)),
                ('source', models.CharField(default='server-final', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_result', to='focus_sessions.focussession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('content_relevance', 'Content relevance'), ('focus_continuity', 'Focus continuity'), ('tab_stability', 'Tab stability'), ('distraction_penalty', 'Distraction penalty')], max_length=32)),
                ('label', models.CharField(max_length=80)),
                ('value', models.FloatField()),
                ('weight', models.FloatField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='scoring.focusscore')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddIndex(
            model_name='focusscore',
            index=models.Index(fields=['user', 'calculated_at'], name='scoring_foc_user_id_918f19_idx'),
        ),
        migrations.AddIndex(
            model_name='focusscore',
            index=models.Index(fields=['user', 'focus_state'], name='scoring_foc_user_id_f980a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='scorecomponent',
            constraint=models.UniqueConstraint(fields=('score', 'key'), name='unique_focus_score_component_key'),
        ),
    ]
