# Generated by Django 6.0.5 on 2026-06-05 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField()),
                ('browser_event_id', models.UUIDField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('session_goal', models.TextField(blank=True)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('content_snippet', models.TextField(blank=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('is_relevant', models.BooleanField(default=False)),
                ('focus_state', models.CharField(choices=[('focused', 'Focused'), ('potentially_distracted', 'Potentially Distracted'), ('distracted', 'Distracted'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='ai_aianalys_session_21f983_idx'), models.Index(fields=['relevance_score'], name='ai_aianalys_relevan_35fff9_idx'), models.Index(fields=['focus_state'], name='ai_aianalys_focus_s_de5eda_idx'), models.Index(fields=['is_relevant'], name='ai_aianalys_is_rele_e69698_idx')],
            },
        ),
    ]
