# Generated by Codex on 2026-06-09

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("focus_sessions", "0002_seed_goal_templates"),
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("observations", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AI", "AI"),
                            ("RULE_BASED_FALLBACK", "Rule-based fallback"),
                        ],
                        max_length=32,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insight",
                        to="focus_sessions.focussession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "updated_at"],
                        name="ai_sessioni_status_80816b_idx",
                    ),
                ],
            },
        ),
    ]
