# Generated by Codex on 2026-06-09

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("focus_sessions", "0002_seed_goal_templates"),
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.UUIDField()),
                ("browser_event_id", models.UUIDField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("session_goal", models.TextField(blank=True)),
                ("page_title", models.CharField(blank=True, max_length=500)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("content_snippet", models.TextField(blank=True)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("is_relevant", models.BooleanField(default=False)),
                (
                    "focus_state",
                    models.CharField(
                        choices=[
                            ("focused", "Focused"),
                            (
                                "potentially_distracted",
                                "Potentially Distracted",
                            ),
                            ("distracted", "Distracted"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "created_at"],
                        name="ai_aianalys_session_21f983_idx",
                    ),
                    models.Index(
                        fields=["relevance_score"],
                        name="ai_aianalys_relevan_35fff9_idx",
                    ),
                    models.Index(
                        fields=["focus_state"],
                        name="ai_aianalys_focus_s_de5eda_idx",
                    ),
                    models.Index(
                        fields=["is_relevant"],
                        name="ai_aianalys_is_rele_e69698_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("observations", models.JSONField(blank=True, default=list)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AI", "AI"),
                            ("RULE_BASED_FALLBACK", "Rule-based fallback"),
                        ],
                        max_length=32,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_insight",
                        to="focus_sessions.focussession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "updated_at"],
                        name="ai_sessioni_status_80816b_idx",
                    ),
                ],
            },
        ),
    ]
