# Generated by Django 6.0.5 on 2026-06-13 12:31

import django.utils.timezone
from django.db import migrations, models


def normalize_existing_document_summaries(apps, schema_editor):
    DocumentSummary = apps.get_model("ai", "DocumentSummary")
    DocumentSummary.objects.filter(mode="key-points").update(mode="key_points")
    DocumentSummary.objects.exclude(content="").update(status="completed")


def reverse_normalize_existing_document_summaries(apps, schema_editor):
    DocumentSummary = apps.get_model("ai", "DocumentSummary")
    DocumentSummary.objects.filter(mode="key_points").update(mode="key-points")


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_sessioninsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsummary',
            name='chunk_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='generation_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='input_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='source_character_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='source_truncated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='source_word_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('stale', 'Stale')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='structured_content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='mode',
            field=models.CharField(choices=[('key_points', 'Key points'), ('detailed', 'Detailed')], max_length=16),
        ),
        migrations.AlterField(
            model_name='documentsummary',
            name='source',
            field=models.CharField(default='ai', max_length=32),
        ),
        migrations.RunPython(
            normalize_existing_document_summaries,
            reverse_normalize_existing_document_summaries,
        ),
        migrations.AddIndex(
            model_name='documentsummary',
            index=models.Index(fields=['document', 'mode', 'status'], name='ai_document_documen_ff2ede_idx'),
        ),
        migrations.AddIndex(
            model_name='documentsummary',
            index=models.Index(fields=['input_checksum'], name='ai_document_input_c_36b3ce_idx'),
        ),
    ]
