# Generated by Django 6.0.5 on 2026-06-13 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_documentsummary_chunk_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcarddeck',
            name='error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='generated_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='generation_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='generation_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='model_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='requested_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='scope',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='source_character_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='source_checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='source_truncated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcarddeck',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('stale', 'Stale')], default='completed', max_length=16),
        ),
        migrations.AddIndex(
            model_name='flashcarddeck',
            index=models.Index(fields=['generation_fingerprint'], name='ai_flashcar_generat_12ff20_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcarddeck',
            index=models.Index(fields=['document', 'status'], name='ai_flashcar_documen_d8735b_idx'),
        ),
    ]
