# Generated by Django 6.0.5 on 2026-07-13 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_ai_token_usage_calibration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAIJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXTRACTING', 'Extracting'), ('CHUNKING', 'Chunking'), ('PROCESSING_CHUNKS', 'Processing chunks'), ('REDUCING', 'Reducing'), ('GENERATING_SUMMARY', 'Generating summary'), ('GENERATING_FLASHCARDS', 'Generating flashcards'), ('FINALIZING', 'Finalizing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=32)),
                ('current_operation', models.CharField(blank=True, max_length=64)),
                ('current_chunk_index', models.PositiveSmallIntegerField(default=0)),
                ('total_chunks', models.PositiveSmallIntegerField(default=0)),
                ('completed_chunks', models.PositiveSmallIntegerField(default=0)),
                ('rolling_context_summary', models.TextField(blank=True)),
                ('entity_memory_json', models.JSONField(blank=True, default=dict)),
                ('open_context_json', models.JSONField(blank=True, default=list)),
                ('chunk_summaries_json', models.JSONField(blank=True, default=list)),
                ('flashcard_candidates_json', models.JSONField(blank=True, default=list)),
                ('last_ai_request_at', models.DateTimeField(blank=True, null=True)),
                ('next_ai_request_at', models.DateTimeField(blank=True, null=True)),
                ('summary_status', models.CharField(default='pending', max_length=32)),
                ('flashcard_status', models.CharField(default='pending', max_length=32)),
                ('notification_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=32)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_job', to='ai.studydocument')),
                ('flashcard_deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to='ai.flashcarddeck')),
                ('summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to='ai.documentsummary')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAIChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('RETRY_SCHEDULED', 'Retry scheduled'), ('FAILED', 'Failed')], default='PENDING', max_length=24)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('partial_result', models.JSONField(blank=True, default=dict)),
                ('updated_context_summary', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_request_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_ai_chunks', to='ai.airequestusage')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.documentaijob')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='documentaijob',
            index=models.Index(fields=['user', 'created_at'], name='ai_document_user_id_e0203a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaijob',
            index=models.Index(fields=['document', 'status'], name='ai_document_documen_224c60_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaijob',
            index=models.Index(fields=['status', 'next_ai_request_at'], name='ai_document_status_138348_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaichunk',
            index=models.Index(fields=['job', 'status', 'chunk_index'], name='ai_document_job_id_aaecb7_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentaichunk',
            constraint=models.UniqueConstraint(fields=('job', 'chunk_index'), name='unique_document_ai_chunk_index'),
        ),
    ]
